# Generated by Django 2.2.7 on 2019-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('code', models.IntegerField(choices=[(92, 'Pakistan'), (91, 'India')])),
                ('number', models.CharField(max_length=50)),
                ('feedback', models.TextField(max_length=1000)),
            ],
        ),
    ]
