# Generated by Django 2.2.7 on 2019-11-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedbackform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackForm',
            new_name='Feedback',
        ),
    ]
