# Generated by Django 2.2.7 on 2019-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191127_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='country',
            field=models.IntegerField(choices=[(91, 'India'), (92, 'Pakistan'), (86, 'China'), (1, 'Canada'), (33, 'France'), (61, 'Australia')]),
        ),
    ]
